# Generated by Django 3.1.2 on 2020-10-06 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('IN_PROGRESS', 'In Progress'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure')], default='QUEUED', max_length=11)),
                ('repo_name', models.CharField(max_length=30, unique=True)),
                ('findings', models.JSONField()),
                ('queued_at', models.DateTimeField(auto_now_add=True)),
                ('scanning_at', models.DateTimeField(null=True)),
                ('finished_at', models.DateTimeField(null=True)),
            ],
        ),
    ]
