# Generated by Django 3.1.2 on 2020-10-07 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanresult',
            name='queued_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='scanresult',
            name='repo_name',
            field=models.CharField(max_length=30),
        ),
    ]
